### ISSUE TITLE
AI assist badge

### ISSUE THREAD

**Issue by samyakkkk** [HeyPuter/Oops.js#2]
Hi! love your work with the repo. 

I trained an AI assist on the code + issues that can help users understand how the repo works and using it.
 
https://app.commanddash.io/agent?github=https://github.com/HeyPuter/Oops.js
 
Please feel free to mention it in the readme if you'd like! best wishes.

<a href="https://app.commanddash.io/agent?github=https://github.com/HeyPuter/Oops.js"><img src="https://img.shields.io/badge/AI-Code%20Assist-EB9FDA"></a>

```
<a href="https://app.commanddash.io/agent?github=https://github.com/HeyPuter/Oops.js"><img src="https://img.shields.io/badge/AI-Code%20Assist-EB9FDA"></a>
```

**Comment by jelveh** [comment]
Hi @samyakkkk, thanks for sharing your projects, it's very exciting idea. 
For the time being though I'm going to pass. Maybe in the future we'll revisit.
